### ISSUE TITLE
unable to startup the server for tabpy in cmd 

### ISSUE THREAD

**Issue by amruutharao** [tableau/TabPy#200]
Traceback (most recent call last):
  File "tabpy.py", line 279, in <module>
    class EndpointsHandler(ManagementHandler):
  File "tabpy.py", line 287, in EndpointsHandler
    @tornado.web.asynchronous
AttributeError: module 'tornado.web' has no attribute 'asynchronous'

"I get the above error in my Command prompt after installation of tab py server .I have tried to install te tabpy server using the below link.(https://github.com/tableau/TabPy) . I followed the instructions and could see that the installation is successfull but the server is not sniffing the port or i am not able to start "tabpy package"

**Comment by 0golovatyi** [comment]
@amruutharao What Python version do you run (python -V) and what version is Tornado package (pip list)?

Also what is the scenario to repro the failure?

**Comment by amruutharao** [comment]
> @amruutharao What Python version do you run (python -V) and what version is Tornado package (pip list)?
> 
> Also what is the scenario to repro the failure?

I use python 3.7 and it has tornodo 6.0. 
I tried it with 3.68 as well and it was throwing the same error.

**Comment by 0golovatyi** [comment]
@amruutharao Would it be possible for you to try with Tornado 5.1.1? There are some incompatibilities with the new release we were hit with before and this is why we are locked to 5.1.1 at the moment.

**Comment by 0golovatyi** [comment]
@amruutharao to try if it works with Tornado 5.1.1 run 'pip install Tornado==5.1.1` (you can confirm version with `pip list`).

**Comment by makks** [comment]
tx 0golovatyi .. I had the exact same issue and your solution worked! I run Python 3.5.4 and after downgrading Tornado to 5.1.1 it works!

**Comment by alicino** [comment]
@makks , thank you for your help!
I just installed the tornado 5.1.1 (downgraded my version 6) and it is working properly.

**Comment by karnapatel** [comment]
> @amruutharao Would it be possible for you to try with Tornado 5.1.1? There are some incompatibilities with the new release we were hit with before and this is why we are locked to 5.1.1 at the moment.

you are a lifesaver !!!! thank you so much.. i got exhausted searching for the right fix !! this totally worked !!

**Comment by FrancesOkolo** [comment]
It worked Thank you. but I have a new error
```
Initializing TabPy...
Done initializing TabPy.
Traceback (most recent call last):
  File "tabpy.py", line 761, in <module>
    main()
  File "tabpy.py", line 756, in main
    application.listen(port)
  File "C:\Users\Awele\AppData\Roaming\Python\Python37\site-packages\tornado\web.py", line 2042, in listen
    server.listen(port, address)
  File "C:\Users\Awele\AppData\Roaming\Python\Python37\site-packages\tornado\tcpserver.py", line 143, in listen
    sockets = bind_sockets(port, address=address)
  File "C:\Users\Awele\AppData\Roaming\Python\Python37\site-packages\tornado\netutil.py", line 168, in bind_sockets
    sock.bind(sockaddr)
OSError: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted

```

**Comment by 0golovatyi** [comment]
@FrancesOkolo Looks like TabPy can't start because there's some other process running on the port. What version of TabPy do you use and what is your configuration for it?

**Comment by FrancesOkolo** [comment]
> @FrancesOkolo Looks like TabPy can't start because there's some other process running on the port. What version of TabPy do you use and what is your configuration for it?

I'm really new to this so I'm not sure. I got Tabpy v0.6.1 and Python 3.7.4

**Comment by 0golovatyi** [comment]
@FrancesOkolo I assume you are trying to run TabPy on a Windows machine with the default configuration. By default, TabPy uses port 9004, update the following command accordingly if you are using a different port. There are 2 options for how to solve the problem:

1. Check what process listens to the port:
```sh
netstat -aon | find /i "listening" | find "9004"
```

In the output for the command, you'll see PID in the last column. Now you can kill the process with
```sh
kill <PID>
```

2. Use a different port for TabPy - see instructions at https://github.com/tableau/TabPy/blob/master/docs/server-config.md for how to create/update configuration file.

**Comment by azharmajeed** [comment]
Hey, does anyone know how to downgrade the tornado package to 5.1.1 in conda without effecting any of it's other dependencies?

**Comment by aru94** [comment]
When I run the startup.bat, it opens and automatically closes. Any suggestions would help me configuring Tableau and python.

**Comment by 0golovatyi** [comment]
@aru94 What steps are you following? There's no `startup.bat` you need to run for starting TabPy.
